name: Setup WP-CLI

description: Downloads and installs the WP-CLI binary.

branding:
  icon: terminal
  color: gray-dark

runs:
  using: 'composite'
  steps:

    - name: Install WP-CLI
      shell: bash
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        chmod +x wp-cli.phar
        sudo mv wp-cli.phar /usr/local/bin/wp
